export HISTIGNORE="&:??:[ ]*:clear:exit:logout"

# Binaries with dependent library files etc here
export PATH="$HOME/dotfiles/neovim/bin:$PATH"

# Single file binaries
export PATH="$HOME/dotfiles/bin:$PATH"

# Time savers
alias ..="cd .."
alias gs="git status"
alias gd="git diff"
