# Clean up bash history
export HISTIGNORE="&:??:[ ]*:clear:exit:logout"

# Binaries with dependent library files in their own subdirectories
export PATH="$HOME/dotfiles/neovim/bin:$PATH"

# Single file binaries
export PATH="$HOME/dotfiles/bin:$PATH"

# Time savers
alias ..="cd .."
alias gs="git status"
alias gd="git diff"

# Danger zone
alias mv="mv -i"
alias rm="rm -i"

alias wa="watch -n 0,1 "
